"""
Source: Backend Schema v2 §9 / Impl Plan v2.1 §1.8's carve-out (Decisions.md
decision 14) -- `tests/fixtures/handmade_40.jsonl` and its expected-values
companion must NOT be generated by the implementation agent. This test
exists so the gate is real the moment a human supplies those files; until
then it xfails with a named reason rather than failing the suite or, worse,
being quietly skipped where nobody would notice its absence.

Fixture format (Day-3 Plan §6, for the human author):
  - tests/fixtures/handmade_40.jsonl -- 40 events, same shape as
    golden.jsonl: {seq, t_ms, event_id, card_hash, bin, ip, session_id,
    amount_minor, currency}.
  - tests/fixtures/handmade_40.expected.jsonl -- one line per event,
    {"seq": n, "features": {"attempts_per_ip_60s": 3, ...}}. Only the
    features actually hand-computed need be present; this test checks
    exactly the keys named and ignores the rest, so a partial file is a
    valid, useful oracle.
  - tests/fixtures/handmade_40.sha256 -- sha256sum --text format, matching
    golden.sha256's two-space text-mode separator.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from packages.features.compute import FeatureContext, classify_ua, compute_features
from packages.features.memory_store import InMemoryWindowStore

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "tests" / "fixtures"
EVENTS_PATH = FIXTURES_DIR / "handmade_40.jsonl"
EXPECTED_PATH = FIXTURES_DIR / "handmade_40.expected.jsonl"
SHA_PATH = FIXTURES_DIR / "handmade_40.sha256"

FIXTURE_PRESENT = EVENTS_PATH.exists() and EXPECTED_PATH.exists() and SHA_PATH.exists()
MERCHANT_ID = "merchant_handmade"


def _parse_sha256sum_file(path: Path) -> dict:
    entries = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, filename = line.partition("  ")
        assert digest and filename, f"malformed sha256sum line: {line!r}"
        entries[filename.strip()] = digest.strip()
    return entries


@pytest.mark.xfail(
    not FIXTURE_PRESENT,
    reason=(
        "tests/fixtures/handmade_40.{jsonl,expected.jsonl,sha256} have not "
        "been authored yet. Per Impl Plan v2.1 §1.8 / Decisions.md decision "
        "14, this fixture and its expected values must be computed on paper "
        "by a human and are carved out of the implementation agent's scope "
        "entirely -- this test does not, and must not, generate them."
    ),
    strict=False,
)
def test_handmade_40_matches_hand_computed_features():
    if not FIXTURE_PRESENT:
        pytest.fail("handmade_40 fixture files are not present yet")

    sha_entries = _parse_sha256sum_file(SHA_PATH)
    for filename in ("handmade_40.jsonl", "handmade_40.expected.jsonl"):
        assert filename in sha_entries, f"{SHA_PATH} does not list {filename}"
        actual_digest = hashlib.sha256((FIXTURES_DIR / filename).read_bytes()).hexdigest()
        assert actual_digest == sha_entries[filename], (
            f"{filename}: committed hash does not match a fresh SHA-256 of "
            f"the committed bytes -- the fixture was edited without "
            f"regenerating handmade_40.sha256"
        )

    events = [json.loads(line) for line in EVENTS_PATH.read_text(encoding="utf-8").splitlines() if line.strip()]
    expected_by_seq = {}
    for line in EXPECTED_PATH.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        expected_by_seq[row["seq"]] = row["features"]

    store = InMemoryWindowStore()
    ua_class = classify_ua("")
    for ev in events:
        ctx = FeatureContext(
            merchant_id=MERCHANT_ID,
            attempt_uid=ev["event_id"],
            ingest_ms=ev["t_ms"],
            payload_digest=f"digest-{ev['event_id']}",
            event_id=ev["event_id"],
            ip=ev["ip"],
            ua_class=ua_class,
            card_hash=ev["card_hash"],
            bin=ev["bin"],
            amount_minor=ev["amount_minor"],
            session_id=ev.get("session_id"),
        )
        fv = compute_features(store, ctx)
        expected = expected_by_seq.get(ev["seq"], {})
        for feature_name, expected_value in expected.items():
            actual_value = fv.values.get(feature_name, fv.snapshot().get(feature_name))
            assert actual_value == expected_value, (
                f"seq {ev['seq']} feature {feature_name!r}: "
                f"expected {expected_value} (hand-computed), got {actual_value}"
            )
